parameters:
- name: jobTitle
  type: string 
  default: ''
- name: dependsOn
  type: string
  default: ''
- name: displayName
  type: string
  default: ''
- name: steps
  type: stepList
  default: []
- name: matrix
  type: object
  default:
    linux-netcore:
      imageName: ubuntu-18.04
      targetFrameworkMoniker: netcoreapp3.1
    mac-netcore:
      imageName: macos-10.15
      targetFrameworkMoniker: netcoreapp3.1
    windows-netcore:
      imageName: windows-2019
      targetFrameworkMoniker: netcoreapp3.1
    windows-netfx:
      imageName: windows-2019
      targetFrameworkMoniker: net46

jobs:
- job: ${{ parameters.jobTitle }}
  dependsOn: ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  timeoutInMinutes: 10
  variables:
    GOBIN:  '$(GOPATH)/bin'
    GOPATH: '$(System.DefaultWorkingDirectory)/gopath'

  strategy:
    matrix: ${{ parameters.matrix }}
  pool:
    vmImage: $(imageName)

  steps: ${{ parameters.steps }}
