stages:
- stage: Deploy
  condition: and (succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ))
  dependsOn: Test
  jobs:
  - deployment: DeployArtifacts
    environment: Prod
    displayName: Deploys artifacts
    timeoutInMinutes: 10
    pool:
      vmImage: ubuntu-18.04
    cancelTimeoutInMinutes: 5
    strategy: 
      runOnce:
        deploy:
          steps:
          - checkout: none
          - download: none 

          - task: DownloadPipelineArtifact@2
            displayName: Download Nuget artifacts
            inputs:
              targetpath: ./
              patterns: |
                package/**/*
              artifactname: binaries

          - script: >-
              dotnet nuget push
              -s https://api.nuget.org/v3/index.json
              -k $NUGET_TOKEN
              ./package/*
            displayName: Push Nuget artifacts
            env:
              NUGET_TOKEN: $(nuget_org_push_new_versions)
