stages:
- stage: Build
  jobs:
  - template: platform-dependent-job.yml
    parameters:
      jobTitle: BuildBinaries
      displayName: Build solution
      matrix:
        linux:
          imageName: ubuntu-18.04
        mac:
          imageName: macos-10.15
        windows:
          imageName: windows-2019
      steps:
      - script: dotnet nuget disable source "Microsoft Visual Studio Offline Packages" # Restore frequently fails when using it
        displayName: Disable Nuget source "Microsoft Visual Studio Offline Packages"
        condition: eq(variables['Agent.OS'], 'Windows_NT') # Not an issue on Linux and MacOS obviously

      - script: >-
          dotnet build ./src/NATS.sln
          --configuration Release
          --no-incremental
          -p:TreatWarningsAsErrors=true
          -p:Version=$(SemVer)
        displayName: Build solution

      - script: >-
          dotnet pack ./src/NATS.Client/
          --configuration Release
          --no-build
          --include-symbols
          --output ./package
          -p:Version=$(SemVer)
        displayName: Package NATS.Client

      - publish: ./
        displayName: Publish binaries for use in dependent jobs
        condition: eq(variables['Agent.OS'], 'Windows_NT') # We only use the binaries from the Windows built, it produces net46 and netstandard1.6 DLLs
        artifact: binaries
